LAB_NUM = 1
OUTPUT_NAME = bin_lab$(LAB_NUM)

TARGET = preamble/lab1.c

Target:
	/opt/homebrew/opt/llvm/bin/clang -fopenmp ${TARGET} -I/opt/homebrew/opt/libomp/include -L/opt/homebrew/opt/libomp/lib -o ${OUTPUT_NAME}
